In [5]:
#導入演算法及數據集
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import operator
import random

In [6]:
def knn(x_test, x_data, y_data, k):
    #計算樣本數量
    x_data_size = x_data.shape[0]
    #複製x_test
    np.tile(x_test, (x_data_size,1))
    #計算x_test與每一個樣本的差
    diffMat = np.tile(x_test, (x_data_size,1)) -x_data
    #計算差值平方
    sqDiffMat = diffMat**2
    #求和
    sqDistances = sqDiffMat.sum(axis=1)
    #開方
    distances = sqDistances**0.5
    #從小到大排序
    sortedDistances = distances.argsort()
    classCount = {}
    for i in range(k):
        #獲取標籤
        votelabel = y_data[sortedDistances[i]]
        #統計標籤數量
        classCount[votelabel] = classCount.get(votelabel,0) + 1
    #根據operator.itemgetter(1) - 第一個值對classCount排序，然後再取倒序
    sortedClassCount = sorted(classCount.items(),key=operator.itemgetter(1),reverse = True)
    #獲取數量最多的標籤
    return sortedClassCount[0][0]

In [7]:
#載入數據
iris = datasets.load_iris()
#x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, iris_size = 0.2)
#分割數據0.2為測試，0.8為訓練

#打亂數據
data_size = iris.data.shape[0]
index = [i for i in range(data_size)]
random.shuffle(index)
iris.data = iris.data[index]
iris.target = iris.target[index]

#切分數據集
test_size = 40
x_train =iris.data[test_size:]
x_test = iris.data[:test_size]
y_train = iris.target[test_size:]
y_test = iris.target[:test_size]

predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i], x_train, y_train, 5))
    
print(classification_report(y_test, predictions)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.92      0.96        12
           2       0.92      1.00      0.96        11

    accuracy                           0.97        40
   macro avg       0.97      0.97      0.97        40
weighted avg       0.98      0.97      0.97        40



In [9]:
print(confusion_matrix(y_test,predictions))

[[17  0  0]
 [ 0 11  1]
 [ 0  0 11]]
